# Generated by Django 3.1.7 on 2021-02-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='workCondition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
