# Generated by Django 3.1.7 on 2021-02-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_auto_20210221_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
