# Generated by Django 3.1.7 on 2021-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_auto_20210322_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
