# Generated by Django 3.1.3 on 2021-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0010_auto_20210412_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Job Post..', max_length=255),
        ),
    ]
