# Generated by Django 3.2 on 2021-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0011_job_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
